### ISSUE TITLE
FilePreview get wrong extension when the path has format like xx.xx.pdf

### ISSUE THREAD

**Issue by CodeByZack** [idea2app/MobX-RESTful-table#13]
<img width="729" alt="img_v2_1e79e64a-d5cd-45b1-9dfc-f2e87a16838g" src="https://github.com/idea2app/MobX-RESTful-table/assets/17472882/9e20eee6-0d92-4eb8-981f-86a8c51ff66d">

[code location](https://github.com/idea2app/MobX-RESTful-table/blob/f3fd1fd/source/FilePreview.tsx#L14)

**Comment by TechQuery** [comment]
fixed by 5947c5e
